#!/bin/sh
#IV="6ec1467f4c0020d4d89f80d0e2c00138"
#KEY="1e288dcebdd82565a3cfd5a25c05921ed7bb25f28d3fa8a4b71b7b3ae6e6c138"
#CIPHER="vZEQYYCoR2WUfo4pxECC0GfiuUlS6LsYWZ1fZ9TGFnxifIYMEMXNCP8B6psyv4PWXDWpwzVQ43f1txrT0IxyOfqH6K3MVAe5cwMa8MMfW+9l96l4wzYbBUDZeSntme1a+lbmvnOQdeiGBmnntLZBAQ=="
#IGNORE=4

. "./$1"

echo '#ifndef CONFIG_H' > config.h
echo '#define CONFIG_H' >> config.h
echo >> config.h
echo "#define IGNORE $IGNORE" >> config.h
echo >> config.h
echo static byte iv[] = \"$(echo $IV | sed 's/../\\x&/g')\"\; >> config.h
echo static byte key[] = \"$(echo $KEY | sed 's/../\\x&/g')\"\; >> config.h
echo static byte cipher[] = \"$(echo $CIPHER | base64 -d | xxd -p | tr -d '\n' | sed 's/../\\x&/g')\"\; >> config.h
echo >> config.h
echo '#endif /* CONFIG_H */' >> config.h
