# Generated by Django 2.2.6 on 2019-11-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191118_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='accpt',
            field=models.BooleanField(default=False),
        ),
    ]
