# Generated by Django 2.2.6 on 2019-11-18 01:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnconfirmedTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=26, validators=[django.core.validators.RegexValidator(message='Invalid account number', regex='^\\d{26}$')])),
                ('title', models.CharField(max_length=100)),
                ('amnt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('accnt', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=26, validators=[django.core.validators.RegexValidator(message='Invalid account number', regex='^\\d{26}$')])),
                ('title', models.CharField(max_length=100)),
                ('amnt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('accnt', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
