# Generated by Django 2.2.6 on 2019-11-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='accnt',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='unconfirmedtransfer',
            old_name='accnt',
            new_name='user',
        ),
    ]
